/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportSessionIdRouteImport } from './routes/report.$sessionId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiUploadCamRouteImport } from './routes/api/upload-cam'
import { Route as ApiTtsAvatarRouteImport } from './routes/api/tts-avatar'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as AgentsSessionIdRouteImport } from './routes/agents.$sessionId'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSessionIdRoute = ReportSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ReportRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCamRoute = ApiUploadCamRouteImport.update({
  id: '/api/upload-cam',
  path: '/api/upload-cam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsAvatarRoute = ApiTtsAvatarRouteImport.update({
  id: '/api/tts-avatar',
  path: '/api/tts-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSessionIdRoute = AgentsSessionIdRouteImport.update({
  id: '/agents/$sessionId',
  path: '/agents/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRouteWithChildren
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-avatar': typeof ApiTtsAvatarRoute
  '/api/upload-cam': typeof ApiUploadCamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRouteWithChildren
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-avatar': typeof ApiTtsAvatarRoute
  '/api/upload-cam': typeof ApiUploadCamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/interview': typeof InterviewRoute
  '/report': typeof ReportRouteWithChildren
  '/agents/$sessionId': typeof AgentsSessionIdRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-avatar': typeof ApiTtsAvatarRoute
  '/api/upload-cam': typeof ApiUploadCamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/history'
    | '/interview'
    | '/report'
    | '/agents/$sessionId'
    | '/api/stripe-webhook'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-avatar'
    | '/api/upload-cam'
    | '/auth/callback'
    | '/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/history'
    | '/interview'
    | '/report'
    | '/agents/$sessionId'
    | '/api/stripe-webhook'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-avatar'
    | '/api/upload-cam'
    | '/auth/callback'
    | '/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/history'
    | '/interview'
    | '/report'
    | '/agents/$sessionId'
    | '/api/stripe-webhook'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-avatar'
    | '/api/upload-cam'
    | '/auth/callback'
    | '/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
  InterviewRoute: typeof InterviewRoute
  ReportRoute: typeof ReportRouteWithChildren
  AgentsSessionIdRoute: typeof AgentsSessionIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsAvatarRoute: typeof ApiTtsAvatarRoute
  ApiUploadCamRoute: typeof ApiUploadCamRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$sessionId': {
      id: '/report/$sessionId'
      path: '/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof ReportSessionIdRouteImport
      parentRoute: typeof ReportRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-cam': {
      id: '/api/upload-cam'
      path: '/api/upload-cam'
      fullPath: '/api/upload-cam'
      preLoaderRoute: typeof ApiUploadCamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-avatar': {
      id: '/api/tts-avatar'
      path: '/api/tts-avatar'
      fullPath: '/api/tts-avatar'
      preLoaderRoute: typeof ApiTtsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$sessionId': {
      id: '/agents/$sessionId'
      path: '/agents/$sessionId'
      fullPath: '/agents/$sessionId'
      preLoaderRoute: typeof AgentsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportRouteChildren {
  ReportSessionIdRoute: typeof ReportSessionIdRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportSessionIdRoute: ReportSessionIdRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
  InterviewRoute: InterviewRoute,
  ReportRoute: ReportRouteWithChildren,
  AgentsSessionIdRoute: AgentsSessionIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsAvatarRoute: ApiTtsAvatarRoute,
  ApiUploadCamRoute: ApiUploadCamRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
